shopapp.webui/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using shopapp.business.Abstract;
using shopapp.entity;
using shopapp.webui.Extensions;
using shopapp.webui.Identity;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    [Authorize]
    public class CardController:Controller
    {
        private ICardService _cardService;
        private IOrderService _orderService;
        private UserManager<User> _userManager;
        public CardController(ICardService cardService,UserManager<User> userManager,IOrderService orderService)
        {
            _userManager = userManager;
            _cardService = cardService;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var card = _cardService.GetCardByUserId(_userManager.GetUserId(User));
            return View(new CardModel(){
                CardId = card.Id,
                CardItems = card.CardItems.Select(i=>new CardItemModel()
                {
                    CardItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity

                }).ToList()
            });
        }
        [HttpPost]
        public IActionResult AddToCard(int productId,int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cardService.AddToCard(userId,productId,quantity);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult DeleteFromCard(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _cardService.DeleteFromCard(userId,productId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            var card = _cardService.GetCardByUserId(_userManager.GetUserId(User));
            
            var orderModel = new OrderModel();

            orderModel.CardModel = new CardModel()
            {
                CardId = card.Id,
                CardItems = card.CardItems.Select(i=>new CardItemModel()
                {
                    CardItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity

                }).ToList()
            };
            return View(orderModel);
        }    
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var card = _cardService.GetCardByUserId(userId);

                model.CardModel = new CardModel()
                {
                    CardId = card.Id,
                    CardItems = card.CardItems.Select(i=>new CardItemModel()
                    {
                        CardItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity

                    }).ToList()
                };

                var payment = PaymentProcess(model);

                if (payment.Status=="success")
                {
                    SaveOrder(model,payment,userId);
                    ClearCard(model.CardModel.CardId);
                    return View("Success");
                }
                else
                {
                    Console.WriteLine(payment.ErrorMessage);
                    var msg = new AlertMessage()
                    {
                        Message = $"{payment.ErrorMessage}",
                        AlertType = "danger"
                    }; 
                   
                    TempData["message"] = JsonConvert.SerializeObject(msg);        
                }    
            }
            return View(model);
        }
        public IActionResult GetOrders()
        {
            var userId = _userManager.GetUserId(User);
            var orders = _orderService.GetOrders(userId);

            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;
            
            foreach (var order in orders)
            {
                orderModel = new OrderListModel();

                orderModel.OrderId = order.Id;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.Phone = order.Phone;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Email = order.Email;
                orderModel.Address = order.Address;
                orderModel.City = order.City;
                orderModel.OrderState = order.OrderState;
                orderModel.PaymentType = order.PaymentType;

                orderModel.OrderItems = order.OrderItems.Select(i=>new OrderItemModel(){
                    OrderItemId = i.Id,
                    Name = i.Product.Name,
                    Price = (double)i.Price,
                    Quantity = i.Quantity,
                    ImageUrl = i.Product.ImageUrl 

                }).ToList();

                orderListModel.Add(orderModel);
            }

            
            return View("Orders",orderListModel);

        }




        private void ClearCard(int cardId)
        {
            _cardService.ClearCard(cardId);
        }
        private void SaveOrder(OrderModel model, Payment payment, string? userId)
        {
            var order = new Order();
            order.OrderNumber = new Random().Next(111111,999999).ToString();
            order.OrderState = EnumOrderState.completed;
            order.PaymentType = EnumPaymentType.CreditCard;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.UserId = userId;
            order.Address = model.Address;
            order.Phone = model.Phone;
            order.Email = model.Email;
            order.City = model.City;
            order.Note = "Note";

            order.OrderItems = new List<entity.OrderItem>();

            foreach (var item in model.CardModel.CardItems)
            {
                var orderItem = new shopapp.entity.OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId,
                };
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);
        }
        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-HBZfdBW6UtIXgwzr1FNszkjDnFiNZMtS";
            options.SecretKey = "sandbox-zDhG86jQQyH1w0v8Lfm32zJv0zlbpBVA";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
                    
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(111111111,999999999).ToString();
            request.Price = model.CardModel.TotalPrice().ToString();
            request.PaidPrice = model.CardModel.TotalPrice().ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            // paymentCard.CardNumber = "5528790000000008";
            // paymentCard.ExpireMonth = "12";
            // paymentCard.ExpireYear = "2030";
            // paymentCard.Cvc = "123";

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = model.FirstName;
            buyer.Surname = model.LastName;
            buyer.GsmNumber = model.Phone;
            buyer.Email = model.Email;
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();

shopapp.webui/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    public class ShopController:Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService)
        {
            this._productService = productService;
        }

        public IActionResult List(string category,int page=1)
        {   
            const int pageSize=2;
            var productViewModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category 
                },
                Products = _productService.GetProductByCategory(category,page,pageSize)
            };

            return View(productViewModel);
        }
        public IActionResult Details(string url)
        {
            if (url==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails(url);
             
            if (product==null)
            {
                return NotFound();
            }
            return View(new ProductDetailModel{
                Product = product,
                Categories = product.ProductCategories.Select(i=>i.Category).ToList()
            });
        }
        public IActionResult Search(string q)
        {
            var productViewModel = new ProductListViewModel()
            {
                Products = _productService.GetSearchResult(q)
            };

            return View(productViewModel);

        }
        
    }
}

shopapp.webui/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;

namespace shopapp.webui.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            this._categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (RouteData.Values["category"]!=null)
            {
                ViewBag.SelectedCategory = RouteData.Values["category"];
            }
            return View(await _categoryService.GetAll());          
        }
    }

}

shopapp.webui/Views/Shop/Details.cshtml
@model ProductDetailModel

<div class="card">
  <div class="row">
    <div class="col-md-3 p-3">
      <img src="~/images/@Model.Product.ImageUrl" class="img-fluid" style="height: 100%;">
    </div>
    <div class="col-md-9 p-3">
        <h1 class="mb-3">@Model.Product.Name</h1> <hr>

        @foreach (var item in Model.Categories)
        {
          <a asp-controller="Shop" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3" style="color: black;">@item.Name</a>
        }

        <div class="mb-3">
          <h4 class="text-success mb-3">₺@Model.Product.Price</h4>

          <form asp-controller="Card" asp-action="AddToCard" method="post" class="form-inline" style="width:250px;">
              <input type="hidden" name="productId" value="@Model.Product.ProductId">
              <div class="input-group mb-3">
                <input type="number" name="quantity" class="form-control" value=1 min="1" step="1" style="width: px;">
                <div class="input-group-append">
                  <button type="submit" class="btn btn-danger">
                    <i class="fas fa-cart-plus "></i> Add to Card
                  </button>
                </div>
              </div>
          </form>

        </div>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-md-12 mt-3">
      <div class="card">
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p class="p-3">@Html.Raw(Model.Product.Description)</p>
          </blockquote>
        </div>
      </div>  
    </div>
</div>

shopapp.webui/Views/Shop/List.cshtml
@model ProductListViewModel


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">    
            @foreach (var product in Model.Products)                         
            {
                <div class="col-md-4">
                @await Html.PartialAsync("_product",product)
                </div>                                
            }
        </div> 
        <div class="row mt-3">
            <div class="col">
                <nav aria-label="Page navigation example">
                    <ul class="pagination mt-5" style="justify-content: center;">
                         @for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
                         {
                            @if (String.IsNullOrEmpty(Model.PageInfo.CurrentCategory))
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")"><a class="page-link " href="/products?page=@(i+1)">@(i+1)</a></li>
                            }
                            else
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")"><a class="page-link" href="/products/@Model.PageInfo.CurrentCategory?page=@(i+1)">@(i+1)</a></li>
                            }
                            
                         }
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
                          


@section Scripts
{
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
}
@section Css
{
    <link rel="stylesheet" href="~/css/productCard.css">
}

shopapp.webui/Views/Shop/Search.cshtml
@model ProductListViewModel


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">    
            @foreach (var product in Model.Products)                         
            {
                <div class="col-md-4">
                @await Html.PartialAsync("_product",product)
                </div>                                
            }
        </div> 
    </div>
</div>
                          


@section Scripts
{
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
}
@section Css
{
    <link rel="stylesheet" href="~/css/productCard.css">
}